secrets:
  birdeye-key: ${BIRDEYE_KEY}
  helius-key: ${HELIUS_KEY}
  tg-token: ${TG_TOKEN}
  tg-chat: ${TG_CHAT}
  clickhouse-url: ${CLICKHOUSE_URL:jdbc:clickhouse://localhost:8123}
  clickhouse-enabled: ${CLICKHOUSE_ENABLED:true}
  minio-endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  minio-access-key: ${MINIO_ACCESS_KEY:minioadmin}
  minio-secret-key: ${MINIO_SECRET_KEY:minioadmin}
  minio-bucket: ${MINIO_BUCKET:labels}
